theme: jekyll-theme-minimal
title: BTWJ
description: We are Boston Tech Workers for Justice
logo: https://raw.githubusercontent.com/bostontechworkers4justice/bostontechworkers4justice.github.io/master/btwj.jpg

