theme: jekyll-theme-minimal
description: We are Boston Tech Workers for Justice
logo: https://raw.githubusercontent.com/bostontechworkers4justice/bostontechworkers4justice.github.io/master/btwj.jpg
sidebar: [Points of Unity and Vision] (https://bostontechworkers4justice.github.io/points_of_unity_vision)
